export enum REDUCER_ACTION_ENUM {
  SET_BLOCK_LIST = 'SET_BLOCK_LIST',
  SET_IS_DRAG_START = 'SET_IS_DRAG_START',
  SET_ACTION_TYPE = 'SET_ACTION_TYPE',
  SET_PREVIEW_MODE = 'SET_PREVIEW_MODE',
  SET_CURRENT_ITEM = 'SET_CURRENT_ITEM',
  SET_BODY_SETTINGS = 'SET_BODY_SETTINGS',
  SET_SELECTION_RANGE = 'SET_SELECTION_RANGE',
  SET_TEXT_RANGE = 'SET_TEXT_RANGE',
  SET_LANGUAGE = 'SET_LANGUAGE',
  SET_LANGUAGE_LIBRARIES = 'SET_LANGUAGE_LIBRARIES',
}
